### ISSUE TITLE
Issue with Zpool and Ahashpool

### ISSUE THREAD

**Issue by robl45** [tutulino/Megaminer#147]
I just started using this yesterday after using multi pool miner for a week or so.   I am noticing an issue that I noticed with mutipool miner as well.  I use ahashpool, zpool, MPH and Hash Refinery.   Ahash is almost always tops for profitability and mostly mines that pool except randomly it will just switch all the AHASH to Zpool and start mining there.  If I stop the program and restart it , it switches back to Ahash pool again.

**Comment by MikeBuzz** [comment]
I don't see that this is an issue if you look at the profitability difference between Zpool and Ahash, its always very close, but normally ahash is slightly better, also ahash has lower fees, the reason it will sometimes switch to zpool its that when its checking for profit at that exact moment zpool is reporting better, sometimes to could happen for a very short time, but due to the default checking of 600

i am thinking using to many different pools is not ideal, as you are switching more times, i am going to limit to maybe 2 pools for a week or 2

**Comment by robl45** [comment]
I'm thinking of limiting the pools as well.  Zpool however is almost double the fee of Ahash so it doesn't make sense to me that it would be more profitable,  but I am very new to this.  What strikes me as odd on Megaminer and Multipool miner is that as soon as I restart, it switches back to Ahash and will stay on Ahash for hours and hours until randomly switching to zpool and eliminating all Ahash.

**Comment by tutulino** [comment]
Please, test master branch code, I thik i found bug source.
