### ISSUE TITLE
Low difficulty share error with keccak

### ISSUE THREAD

**Issue by bompus** [tutulino/Megaminer#148]
I was getting this error about 50% of the time. To fix, I added this to ccminerAlexisHSR.json, but should be added to all of the ccminer forks for keccak.

before: {"Keccak":"-a keccak"},
after: {"Keccak":"-a keccak -m 2"},

Now I have 100% accepted.

**Comment by MikeBuzz** [comment]
Are you using zpool?

**Comment by bompus** [comment]
@MikeBuzz I noticed this on on ITALYIIMP , didn't check other pools.

**Comment by MikeBuzz** [comment]
yeah it seems it happened with yiimp based pools, MPH does not show the issue

**Comment by MikeBuzz** [comment]
#150

**Comment by MikeBuzz** [comment]
PR submitted

**Comment by cjroepe** [comment]
I concur that adding a multiplier to the difficulty level does fix the issue.

I have also seen that Keccak is often favored as paying a high profit, but I don't think that italyiimp actually pays what the calc says.  It is more like cents per hour instead of dollars.  Not sure if the profit calc on italyiimp is wrong or if it is something else

**Comment by cjroepe** [comment]
I believe the stratum server on Yiimp pools are not talking to ccminer correctly that is why the difficulty level is always too low

**Comment by tutulino** [comment]
Added to master / next release
