### ISSUE TITLE
GPU not being recognized [Not Supported]

### ISSUE THREAD

**Issue by dethknite** [tutulino/Megaminer#241]
Previous 5.1 was working fine with my NVidia 1050ti, but now it keeps throwing the following error in 5.2.
![2018-01-16_15-00-43](https://user-images.githubusercontent.com/965431/35012248-cc7ca644-face-11e7-8468-2ee42bf3253d.png)

**Comment by dethknite** [comment]
Here is a gpulist from 5.1 and 5.2
![gpulist_5 1](https://user-images.githubusercontent.com/965431/35020095-e8a9de88-faef-11e7-9307-b8a6fb0f62a9.png)
![gpulist_5 2](https://user-images.githubusercontent.com/965431/35020097-eafd299c-faef-11e7-817e-c2989cd0b11a.png)

**Comment by dethknite** [comment]
Looks like the issue is the Power calculations when not supported...

**Comment by tutulino** [comment]
It is trying convert "[not supported]" to int value, I will fix next release / master code upload

**Comment by 1001rapid** [comment]
same error loged when bech 980 Ti
create benchmark file whith "PL0" string
but in Current screen Power Limit show correct number

`01/30/2018 08:15:02...... ###### ERROR ##### Cannot add a member with the name "Power_limit_percent" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command. at <ScriptBlock>, D:\Mining\Megaminer\Include.ps1: line 229
at <ScriptBlock>, <No file>: line 1
at get_gpu_information, D:\Mining\Megaminer\Include.ps1: line 206
at <ScriptBlock>, D:\Mining\Megaminer\core.ps1: line 841
at <ScriptBlock>, <No file>: line 1
01/30/2018 08:15:02...... ###### ERROR ##### Cannot convert value " [Not Supported]" to type "System.Int32". Error: "Input string was not in a correct format." at <ScriptBlock>, D:\Mining\Megaminer\Include.ps1: line 212
at <ScriptBlock>, <No file>: line 1
at get_gpu_information, D:\Mining\Megaminer\Include.ps1: line 206
at <ScriptBlock>, D:\Mining\Megaminer\core.ps1: line 841
at <ScriptBlock>, <No file>: line 1
`
