### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by podlbo** [tutulino/Megaminer#348]
I get new error with latest master:
![slika](https://user-images.githubusercontent.com/33230718/36991580-687f228e-20a8-11e8-8f9e-d3f3506952bc.png)
[2018-03-05_18-27-16.txt](https://github.com/tutulino/Megaminer/files/1782051/2018-03-05_18-27-16.txt)

**Comment by tutulino** [comment]
This error is due to no existence of some new variables in config. I have uploaded a new core.ps1 file without that error because is an optional feature and MM can understand absence of variable as "Disabled" but not always can be.

Read always changelog.txt to see if a new code needs new variables.
