### ISSUE TITLE
How to disable a GPU

### ISSUE THREAD

**Issue by Deeferdawg** [tutulino/Megaminer#365]
I would like to know how to disable a gpu from mining. What file do I need to open to be able to do this. Thank you!

**Comment by 1001rapid** [comment]
Use GPUGROUP in config file

**Comment by tutulino** [comment]
as 1001rapid said, you must play with gpu groups as you want. Example for 3 nvidia GPU where we want to disable first gpu.

@@GPUGROUPS={"GroupName" : "allexceptone","Type":"NVIDIA","Gpus":"1,2","PowerLimits":"0"}

also you can define two groups 

@@GPUGROUPS=[{"GroupName" : "allexceptone","Type":"NVIDIA","Gpus":"1,2","PowerLimits":"0"},{"GroupName" : "all","Type":"NVIDIA","Gpus":"0.1,2","PowerLimits":"0"}

and play (always) with batch starting parameter -gpugroups to run one or another group (if you run all groups dont work because there is duplicated gpus between them)
