### ISSUE TITLE
Is benchmarking taking longer than it's supposed to?

### ISSUE THREAD

**Issue by VukaKun** [tutulino/Megaminer#370]
I'm trying to get an estimate for the benchmark time, so I added these lines to _core.ps1_

       `$RemainingBenchmarks = ($ActiveMiners.subminers | where-object NeedBenchmark -eq $true).count       
        if($RemainingBenchmarks -ne 0){
        $ETA = Get-Date
        $BenchmarkETA = New-TimeSpan -seconds ([int] $BenchmarkintervalTime*$RemainingBenchmarks )
        $ETA = $ETA.AddDays($BenchmarkETA.days)
        $ETA = $ETA.AddHours($BenchmarkETA.hours)
        $ETA = $ETA.AddMinutes($BenchmarkETA.minutes)
        $ETA = $ETA.AddSeconds($BenchmarkETA.seconds)
        
        Print_Horizontal_line "$RemainingBenchmarks benchmarks left. ETA: $ETA"
        Print_Horizontal_line
        }`

... but it seems **way** off and it even increases from time to time. What's up with that? If $BenchmarkintervalTime*$RemainingBenchmarks isn't the required benchmark time, then what is?

**Comment by tutulino** [comment]
`$ActiveMiners.subminers | where-object NeedBenchmark -eq $true ` is not true benchmarks left if you use coin level pool like mining pool hub, there is a subminer for each coin but only 1 benchmark for that algo will be done and all coin for that algo will be covered (I know "benchmarks" left number in screen is also false).

Only things that can increase pending benchmarks are:

- Powerlimit feature is enabled and a new algo reach first position for real mining, but this only can happend after a first round of all benchmarks.

- Some pool that before was filtered by @@Minworkers config is not filtered now because has more than configured valued, before had less than that value.
