### ISSUE TITLE
MegaMiner Unstable since last updates

### ISSUE THREAD

**Issue by reset77** [tutulino/Megaminer#408]
Hi Thanks for your time

Recently since last updates MegaMiner has become really unstable
after some random time, maybe minutes or hours some problem happen and MM stop "seeing" one of the GPU groups, very random problem,

Mining stops and MM starts a loop restarting interval again and again

MM used to be really stable, maybe some bug in the last updates? 

Maybe any plans on adding a visual user interface?

Thanks!!

**Comment by vapor99** [comment]
Having the same issues as above

**Comment by bigheadprawn** [comment]
Not sure if the issue you experienced is exactly the one I hit, where at a random time all my GPUs are loss and none of the miners can do the mining until after a power cycle. It turns out the issue was the Nvidia driver issue. By upgrading to the latest version 397.64 and I am no longer seeing the issue for days.

**Comment by tutulino** [comment]
I have not this bug, I had old nvdia drivers ( two month old), I have updated to 397.64 for testing

**Comment by reset77** [comment]
Thanks for the feedback, I also have 397.64 now and it seems the issue is gone, RIG stable for days... good to know it was the driver and not MM

will close this issue now, Thanks!!
